urdix.o: \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
        ../sxx/urdix.sxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx \
        ../sxx/urdip.sxx
urdit.o: \
	../urdit.hxx \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx \
        ../sxx/urdit.sxx \
	../../xpp/initx.hxx
urdi5t.o: \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
urdi4t.o: \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
urdi3t.o: \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
urdi2t.o: \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
buildx.o: \
	../buildx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/xunewx.hxx \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../urdix.hxx \
	../urdix.oxx \
        ../sxx/buildx.sxx
../sxx/urdix.sxx: \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx
../sxx/urdit.sxx: \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
../sxx/urdip.sxx: \
	../../xpp/allocx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
../sxx/buildx.sxx: \
	../../xlatexpp/thunkx.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/xunewx.hxx \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx
sxx:        ../sxx/urdix.sxx \
        ../sxx/urdip.sxx \
        ../sxx/urdit.sxx \
        ../sxx/buildx.sxx \
