timex.o: \
	/usr/local/share/bin/nat2.0/sun4/incl/stream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/iostream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/memory.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/memory.h \
	/usr/local/share/bin/nat2.0/sun4/incl/iomanip.h \
	/usr/local/share/bin/nat2.0/sun4/incl/generic.h \
	/usr/local/share/bin/nat2.0/sun4/incl/stdiostream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/stdio.h \
	/usr/local/share/bin/nat2.0/sun4/incl/errno.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/errno.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/stdio.h \
	/usr/local/share/bin/nat2.0/sun4/incl/fstream.h \
	./timex.hxx \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/stdtypes.h \
	/usr/include/sys/sysmacros.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/time.h \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	./timex.ixx
timet.o: \
	/usr/local/share/bin/nat2.0/sun4/incl/stream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/iostream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/memory.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/memory.h \
	/usr/local/share/bin/nat2.0/sun4/incl/iomanip.h \
	/usr/local/share/bin/nat2.0/sun4/incl/generic.h \
	/usr/local/share/bin/nat2.0/sun4/incl/stdiostream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/stdio.h \
	/usr/local/share/bin/nat2.0/sun4/incl/errno.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/errno.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/stdio.h \
	/usr/local/share/bin/nat2.0/sun4/incl/fstream.h \
	./timex.hxx \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/stdtypes.h \
	/usr/include/sys/sysmacros.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/time.h \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	./timex.ixx
remotex.o: \
	./remotex.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	../../xpp/initx.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/share/bin/nat2.0/sun4/incl/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/share/bin/nat2.0/sun4/incl/stdio.h \
	/usr/local/share/bin/nat2.0/sun4/incl/errno.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/errno.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/stdio.h \
	/usr/local/share/bin/nat2.0/sun4/incl/stream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/iostream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/memory.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/memory.h \
	/usr/local/share/bin/nat2.0/sun4/incl/iomanip.h \
	/usr/local/share/bin/nat2.0/sun4/incl/generic.h \
	/usr/local/share/bin/nat2.0/sun4/incl/stdiostream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/fstream.h \
	/usr/local/share/bin/nat2.0/sun4/incl/setjmp.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/setjmp.h \
	/usr/include/machine/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/garbagex.hxx \
	../../xpp/bibopx.oxx \
	../../xpp/garbagex.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/share/bin/nat2.0/sun4/incl/string.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/stdtypes.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/string.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	/usr/local/share/bin/nat2.0/sun4/incl/osfcn.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/types.h \
	/usr/include/sys/sysmacros.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/ptrace.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/ptrace.h \
	/usr/local/share/bin/nat2.0/sun4/incl/libc.h \
	/usr/local/share/bin/nat2.0/sun4/incl/pwd.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/pwd.h \
	/usr/local/share/bin/nat2.0/sun4/incl/rand48.h \
	/usr/local/share/bin/nat2.0/sun4/incl/regcmp.h \
	/usr/local/share/bin/nat2.0/sun4/incl/signal.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/signal.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/signal.h \
	/usr/include/vm/faultcode.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/wait.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/resource.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/resource.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/wait.h
timex.sxx: \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/types.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/stdtypes.h \
	/usr/include/sys/sysmacros.h \
	/usr/local/share/bin/nat2.0/sun4/incl/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/sys/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/time.h \
	/usr/local/share/bin/nat2.0/sun4/incl/cc/time.h \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	./timex.ixx \
	./timex.hxx
remotex.sxx: \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h
