urdix.o: \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/stat.h \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
        ../sxx/urdix.sxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx \
        ../sxx/urdip.sxx \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/libc.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h
urdit.o: \
	../urdit.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.hxx \
	../urdix.oxx \
	../../xlatexpp/testerx.hxx \
	../../xlatexpp/testerx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/spacex.oxx \
        ../sxx/urdit.sxx
urdi5t.o: \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
urdi4t.o: \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
urdi3t.o: \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
urdi2t.o: \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	../urdix.hxx \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx \
	../urdip.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xpp/fhashx.hxx
buildx.o: \
	../buildx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../urdix.hxx \
	../urdix.oxx \
        ../sxx/buildx.sxx
../sxx/urdix.sxx: \
	../../xpp/bombx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/tofux.hxx \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.oxx
../sxx/urdit.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../urdix.hxx \
	../urdix.oxx \
	../../xlatexpp/testerx.hxx \
	../../xlatexpp/testerx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/spacex.oxx
../sxx/urdip.sxx: \
	../../xpp/allocx.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/fhashx.hxx
../sxx/buildx.sxx: \
	../../xlatexpp/thunkx.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx
sxx:        ../sxx/urdix.sxx \
        ../sxx/urdip.sxx \
        ../sxx/urdit.sxx \
        ../sxx/buildx.sxx \
