scavx.o: \
	../xpp/scavx.hxx \
	../xpp/xcompatx.hxx \
	../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../xpp/scavx.oxx \
	../xpp/scavp.oxx \
	../xpp/scavx.ixx \
	../xpp/scavp.hxx \
	../xpp/scavp.ixx \
	../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../xpp/bombc.h \
	../xpp/bombx.ixx \
	../xpp/parrayx.hxx \
	../xpp/tofux.hxx \
	../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../xpp/opaquex.hxx \
	../xpp/opaquex.ixx \
	../xpp/tofux.oxx \
	../comm/nxcvrx.oxx \
	../xpp/tofux.ixx \
	../xpp/opaque2x.ixx \
	../xpp/intvarx.hxx \
	../xpp/intvarx.ixx \
	../xpp/parrayx.oxx \
	../xlatexpp/primvalx.oxx \
	../stubble/copy.hf \
	../xpp/copyrcpx.hxx \
	../xpp/copyrcpx.oxx \
	../comm/recipex.oxx \
	../comm/recipex.hxx \
	../xpp/initx.hxx \
	../comm/xfrspecx.oxx \
	../comm/nxcvrx.hxx \
	../xpp/parrayx.ixx \
	../xpp/wparrayx.hxx \
	../xpp/wparrayx.oxx \
	../xpp/wparrayx.ixx \
	/usr/local/lang/SC1.0/include/CC/assert.h \
	/usr/local/lang/SC1.0/include/CC/libc.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/sys/mman.h
sxx: