turtlex.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../turtlex.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../turtlex.oxx \
	../../server/shephx.oxx \
	../../xpp/initx.hxx \
	../../server/shephx.hxx \
	../diskmanx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../../xlatexpp/tokensx.oxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../comm/cookbkx.oxx \
	../../server/counterx.oxx \
	../../xlatexpp/setx.oxx \
	../turtlex.ixx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx \
	../turtlep.hxx \
	../turtlep.oxx \
	../turtlep.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nscottyx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xlatexpp/thunkx.hxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
        ../sxx/turtlex.sxx \
        ../sxx/turtlep.sxx
snfinfox.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../snfinfox.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../snfinfox.oxx \
	../../xpp/initx.hxx \
	../flkinfox.oxx \
	../../comm/nscottyx.oxx \
	../../xpp/parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../urdi/urdix.oxx \
	../snfinfox.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../urdi/urdix.hxx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/arrayx.ixx \
	../flkinfox.hxx \
	../../xlatexpp/primtabx.oxx \
	../../server/shephx.oxx \
	../flkinfox.ixx \
	../../comm/nscottyx.hxx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
        ../sxx/snfinfox.sxx
purgingx.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../purgingx.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../purgingx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/gchooksx.hxx \
	../../xpp/initx.hxx \
	../../xpp/wparrayx.hxx \
	../../xpp/parrayx.hxx \
	../../xpp/parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../../xpp/parrayx.ixx \
	../../xpp/wparrayx.oxx \
	../../xpp/wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/fhashx.hxx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../diskmanx.oxx \
	../packerx.oxx \
	../../server/shephx.oxx \
	../purgingx.ixx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../server/counterx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../diskmanx.ixx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../packerx.hxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../purgingp.hxx \
	../purgingp.oxx \
	../purgingp.ixx \
        ../sxx/purgingx.sxx \
        ../sxx/purgingp.sxx
packerx.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../packerx.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../packerx.oxx \
	../diskmanx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../packerp.hxx \
	../../comm/nscottyx.hxx \
	../../comm/schunkx.hxx \
	../../comm/schunkx.ixx \
	../packerp.ixx \
	../../xlatexpp/cachex.hxx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx \
	../../server/granmapx.hxx \
	../../server/granmapx.oxx \
	../../server/brange1x.oxx \
	../../server/brange2x.oxx \
	../../server/brange3x.oxx \
	../../xlatexpp/crossx.oxx \
	../../server/entx.oxx \
	../../xlatexpp/filterx.oxx \
	../../server/idx.oxx \
	../../server/nkernelx.oxx \
	../../xlatexpp/sequencx.oxx \
	../../comm/negoti8x.hxx \
	../../comm/negoti8x.oxx \
	../../comm/negoti8p.oxx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx \
	../../xpp/stringx.hxx \
	../../comm/txtcommx.hxx \
	../../comm/txtcommx.oxx \
        ../sxx/packerx.sxx \
        ../sxx/packerp.sxx
packert.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../packert.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../packerx.hxx \
	../packerx.oxx \
	../diskmanx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../packert.oxx \
	../../comm/nscottyx.hxx \
	../../server/granmapx.oxx \
	../packert.ixx \
	../../server/granmapx.hxx \
	../../server/brange1x.oxx \
	../../server/brange2x.oxx \
	../../server/brange3x.oxx \
	../../xlatexpp/crossx.oxx \
	../../server/entx.oxx \
	../../xlatexpp/filterx.oxx \
	../../server/idx.oxx \
	../../server/nkernelx.oxx \
	../../xlatexpp/sequencx.oxx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx \
	../../comm/negoti8x.hxx \
	../../comm/negoti8x.oxx \
	../../comm/negoti8p.oxx \
	../packerp.hxx \
	../../comm/schunkx.hxx \
	../../comm/schunkx.ixx \
        ../sxx/packert.sxx
flkinfox.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../flkinfox.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../flkinfox.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/shephx.oxx \
	../flkinfox.ixx \
	../diskmanx.hxx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../server/counterx.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../../xlatexpp/tokensx.hxx \
        ../sxx/flkinfox.sxx
fakedskx.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../fakedskp.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../fakedskp.oxx \
	../diskmanx.oxx \
	../turtlex.oxx \
	../../server/shephx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/counterx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../turtlex.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/setx.oxx \
	../fakedskp.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nscottyx.oxx \
        ../sxx/fakedskp.sxx
dstatx.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../dstatp.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../dstatp.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../xlatexpp/thunkx.oxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../comm/nscottyx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../dstatp.ixx \
	../../comm/cookbkx.hxx \
	../../comm/xfrspecx.hxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/negoti8x.hxx \
	../../comm/negoti8x.oxx \
	../../comm/negoti8p.oxx \
	../../comm/nscottyx.hxx \
	../packerp.hxx \
	../packerx.hxx \
	../packerx.oxx \
	../diskmanx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/schunkx.hxx \
	../../comm/schunkx.ixx \
	../../comm/txtcommx.hxx \
	../../comm/txtcommx.oxx \
        ../sxx/dstatp.sxx
diskmanx.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../diskmanx.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../diskmanp.hxx \
	../diskmanp.oxx \
	../diskmanp.ixx \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../packerx.hxx \
	../packerx.oxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
        ../sxx/diskmanx.sxx \
        ../sxx/diskmanp.sxx
diskmant.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../diskmant.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../diskmanx.hxx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../diskmant.oxx \
	../../xlatexpp/testerx.oxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/testerx.hxx \
	../diskmant.ixx \
	../../server/counterx.hxx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx \
	../packert.hxx \
	../packerx.hxx \
	../packerx.oxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../packert.oxx \
	../../comm/nscottyx.hxx \
	../../server/granmapx.oxx \
	../packert.ixx \
	../../server/granmapx.hxx \
	../../server/brange1x.oxx \
	../../server/brange2x.oxx \
	../../server/brange3x.oxx \
	../../xlatexpp/crossx.oxx \
	../../server/entx.oxx \
	../../xlatexpp/filterx.oxx \
	../../server/idx.oxx \
	../../server/nkernelx.oxx \
	../../xlatexpp/sequencx.oxx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx \
        ../sxx/diskmant.sxx
consistt.o: \
	../../xpp/choosex.hxx \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	/usr/local/lang/SC1.0/include/CC/setjmp.h \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../consistt.hxx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../consistt.oxx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../stubble/copy.hf \
	../../xpp/copyrcpx.hxx \
	../../xpp/copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../diskmanx.hxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	/usr/local/lang/SC1.0/include/CC/new.h \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/setx.oxx \
	../consistt.ixx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx \
	../../comm/cookbkx.hxx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx \
	../../xpp/loggerx.hxx \
	../../xpp/loggerx.oxx \
	../../xpp/loggerx.ixx \
	../packerx.hxx \
	../packerx.oxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../../xpp/stringx.hxx \
        ../sxx/consistt.sxx
../sxx/turtlex.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../turtlex.oxx \
	../../server/shephx.oxx \
	../../xpp/initx.hxx \
	../../server/shephx.hxx \
	../diskmanx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xpp/parrayx.oxx \
	../../comm/cookbkx.oxx \
	../../server/counterx.oxx \
	../../xlatexpp/setx.oxx \
	../../comm/xfrspecx.oxx
../sxx/turtlep.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../turtlex.hxx \
	../turtlex.oxx \
	../../server/shephx.oxx \
	../../xpp/initx.hxx \
	../../server/shephx.hxx \
	../diskmanx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xpp/parrayx.oxx \
	../../comm/cookbkx.oxx \
	../../server/counterx.oxx \
	../../xlatexpp/setx.oxx \
	../../comm/xfrspecx.oxx \
	../turtlep.oxx
../sxx/snfinfox.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../snfinfox.oxx \
	../../xpp/initx.hxx \
	../flkinfox.oxx \
	../../comm/nscottyx.oxx \
	../../xpp/parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../urdi/urdix.oxx \
	../snfinfox.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../urdi/urdix.hxx
../sxx/purgingx.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../purgingx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/gchooksx.hxx \
	../../xpp/initx.hxx \
	../../xpp/wparrayx.hxx \
	../../xpp/parrayx.hxx \
	../../xpp/parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xpp/wparrayx.oxx \
	../../xpp/wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/fhashx.hxx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../diskmanx.oxx \
	../packerx.oxx \
	../../server/shephx.oxx \
	../purgingx.ixx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../packerx.hxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../purgingx.hxx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nxcvrx.hxx \
	../../xpp/choosex.hxx
../sxx/purgingp.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../purgingx.hxx \
	../purgingx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/gchooksx.hxx \
	../../xpp/initx.hxx \
	../../xpp/wparrayx.hxx \
	../../xpp/parrayx.hxx \
	../../xpp/parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xpp/wparrayx.oxx \
	../../xpp/wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/fhashx.hxx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../diskmanx.oxx \
	../packerx.oxx \
	../../server/shephx.oxx \
	../purgingx.ixx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../packerx.hxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nxcvrx.hxx \
	../../xpp/choosex.hxx \
	../purgingp.oxx
../sxx/packerx.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../packerx.oxx \
	../diskmanx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../packerx.hxx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nxcvrx.hxx \
	../../xpp/choosex.hxx
../sxx/packert.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../packerx.hxx \
	../packerx.oxx \
	../diskmanx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nxcvrx.hxx \
	../../xpp/choosex.hxx \
	../packert.oxx \
	../../comm/nscottyx.hxx \
	../../server/granmapx.oxx \
	../packert.ixx \
	../../server/granmapx.hxx \
	../../server/brange1x.oxx \
	../../server/brange2x.oxx \
	../../server/brange3x.oxx \
	../../xlatexpp/crossx.oxx \
	../../server/entx.oxx \
	../../xlatexpp/filterx.oxx \
	../../server/idx.oxx \
	../../server/nkernelx.oxx \
	../../xlatexpp/sequencx.oxx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx
../sxx/packerp.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../packerx.hxx \
	../packerx.oxx \
	../diskmanx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/integerx.oxx \
	../../comm/nscottyx.oxx \
	../packerp.oxx \
	../../comm/schunkx.oxx \
	../purgingx.oxx \
	../../xlatexpp/settabx.oxx \
	../../xlatexpp/setx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../packerx.ixx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/arrayx.ixx \
	../../comm/cookbkx.hxx \
	../../server/counterx.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.ixx \
	/usr/local/lang/SC1.0/include/CC/osfcn.h \
	/usr/local/lang/SC1.0/include/CC/sysent.h \
	/usr/local/lang/SC1.0/include/CC/sys/types.h \
	/usr/local/lang/SC1.0/include/CC/sys/sysmacros.h \
	/usr/local/lang/SC1.0/include/CC/sys/ptrace.h \
	/usr/local/lang/SC1.0/include/CC/sys/wait.h \
	/usr/local/lang/SC1.0/include/CC/sys/time.h \
	/usr/local/lang/SC1.0/include/CC/time.h \
	/usr/local/lang/SC1.0/include/CC/stdlib.h \
	/usr/local/lang/SC1.0/include/CC/pwd.h \
	/usr/local/lang/SC1.0/include/CC/errno.h \
	/usr/local/lang/SC1.0/include/CC/sys/errno.h \
	/usr/local/lang/SC1.0/include/CC/malloc.h \
	/usr/local/lang/SC1.0/include/CC/alloca.h \
	../purgingx.hxx \
	../purgingx.ixx \
	../../xlatexpp/settabx.hxx \
	../../xlatexpp/tabentx.oxx \
	../../xlatexpp/settabx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../snfinfox.hxx \
	../snfinfox.ixx \
	../../urdi/urdix.hxx \
	../turtlex.hxx \
	../../comm/xfrspecx.hxx \
	../../comm/nxcvrx.hxx \
	../../xpp/choosex.hxx \
	../../comm/nscottyx.hxx \
	../../comm/schunkx.hxx \
	../../comm/schunkx.ixx
../sxx/flkinfox.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../flkinfox.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../server/shephx.oxx \
	../flkinfox.ixx
../sxx/fakedskp.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../fakedskp.oxx \
	../diskmanx.oxx \
	../turtlex.oxx \
	../../server/shephx.oxx \
	../diskmanx.hxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../turtlex.hxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/setx.oxx
../sxx/dstatp.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../dstatp.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../xlatexpp/thunkx.oxx \
	../../comm/cookbkx.oxx \
	../../comm/nscottyx.oxx \
	../snfinfox.oxx \
	../../urdi/urdix.oxx \
	../../comm/xfrspecx.oxx
../sxx/diskmanx.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx
../sxx/diskmant.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../diskmanx.hxx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../diskmant.oxx \
	../../xlatexpp/testerx.oxx \
	../../server/shephx.hxx \
	../../xlatexpp/tokensx.oxx \
	../../server/shephx.ixx \
	../flkinfox.hxx \
	../flkinfox.ixx \
	../../xlatexpp/tokensx.hxx \
	../../xlatexpp/testerx.hxx
../sxx/diskmanp.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../diskmanx.hxx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../diskmanp.oxx
../sxx/consistt.sxx: \
	../../xpp/tofux.hxx \
	../../xpp/xcompatx.hxx \
	../../xpp/ccompatc.h \
	/usr/local/lang/SC1.0/include/CC/string.h \
	/usr/local/lang/SC1.0/include/CC/c_varieties.h \
	/usr/local/lang/SC1.0/include/CC/sys/stdtypes.h \
	/usr/local/lang/SC1.0/include/CC/memory.h \
	../../xpp/xunewx.hxx \
	/usr/local/lang/SC1.0/include/CC/stddef.h \
	../../xpp/bombx.hxx \
	../../xpp/bombc.h \
	../../xpp/bombx.ixx \
	../../xpp/scavx.hxx \
	../../xpp/scavx.oxx \
	../../xpp/scavp.oxx \
	../../xpp/scavx.ixx \
	../../xpp/opaquex.hxx \
	../../xpp/opaquex.ixx \
	/usr/local/lang/SC1.0/include/CC/stream.h \
	/usr/local/lang/SC1.0/include/CC/iostream.h \
	/usr/local/lang/SC1.0/include/CC/iomanip.h \
	/usr/local/lang/SC1.0/include/CC/generic.h \
	/usr/local/lang/SC1.0/include/CC/stdiostream.h \
	/usr/local/lang/SC1.0/include/CC/stdio.h \
	/usr/local/lang/SC1.0/include/CC/fstream.h \
	../../xpp/tofux.oxx \
	../../comm/nxcvrx.oxx \
	../../xpp/tofux.ixx \
	../../xpp/opaque2x.ixx \
	../../xpp/intvarx.hxx \
	../../xpp/intvarx.ixx \
	../consistt.oxx \
	../diskmanx.oxx \
	../../comm/bootplnx.hxx \
	../../comm/bootplnx.oxx \
	../../xlatexpp/thunkx.oxx \
	../../xpp/initx.hxx \
	../../xlatexpp/thunkx.hxx \
	../../comm/cookbkx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx \
	../diskmanx.hxx \
	../../server/counterx.oxx \
	../../server/shephx.oxx \
	../flkinfox.oxx \
	../../xpp/fluidx.oxx \
	../../xpp/fluidx.hxx \
	../../xpp/fluidx.ixx \
	../turtlex.oxx \
	../../xpp/wparrayx.oxx \
	../../xpp/parrayx.oxx \
	../../comm/xfrspecx.oxx \
	../diskmanx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xpp/parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../xpp/parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../../xpp/wparrayx.hxx \
	../../xpp/wparrayx.ixx \
	../../xpp/fhashx.hxx \
	../../xpp/allocx.hxx \
	../../xpp/queuesx.hxx \
	../../xpp/queuesx.ixx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/setx.oxx
sxx:        ../sxx/turtlex.sxx \
        ../sxx/turtlep.sxx \
        ../sxx/snfinfox.sxx \
        ../sxx/purgingx.sxx \
        ../sxx/purgingp.sxx \
        ../sxx/packerx.sxx \
        ../sxx/packerp.sxx \
        ../sxx/packert.sxx \
        ../sxx/flkinfox.sxx \
        ../sxx/fakedskp.sxx \
        ../sxx/dstatp.sxx \
        ../sxx/diskmanx.sxx \
        ../sxx/diskmanp.sxx \
        ../sxx/diskmant.sxx \
        ../sxx/consistt.sxx \
