pub mod chunk_store;
pub mod counter;
pub mod edition_chunks;
pub mod engine;
pub mod file_storage;
pub mod manifest;
pub mod memory;
pub mod packer;
pub mod persistent;
pub mod snarf;
pub mod transaction;
pub mod traits;
pub mod urdi;

pub use chunk_store::{ChunkStore, ChunkError};
pub use counter::{BatchCounter, Counter, SingleCounter};
pub use engine::{StorageEngine, StorageError, StorageResult};
pub use file_storage::FileBackedStorage;
pub use memory::InMemoryStorage;
pub use packer::SnarfStorage;
pub use persistent::{FlockFlags, FlockId, FlockInfo, FlockLocation, FlockState};
pub use snarf::{Snarf, SnarfStore, DEFAULT_SNARF_SIZE, SNARF_INFO_COUNT};
pub use transaction::Transaction;
pub use traits::{Persistent, PersistentRef, PersistentRegistry, TypeRegistry, DeserializerFn, encode_flock, decode_flock};
pub use urdi::{UrdiFile, UrdiHeader, DEFAULT_SNARF_SIZE_FILE, DEFAULT_INITIAL_COUNT, DEFAULT_STAGE_COUNT, DEFAULT_DATA_START};
