xunewx.o: \
	../allocx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../queuesx.hxx \
	../queuesx.ixx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx
xcompatt.o: \
	../xcompatx.hxx \
	../ccompatc.h
wparrayx.o: \
	../wparrayx.hxx \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../wparrayp.hxx \
        ../sxx/wparrayx.sxx \
        ../sxx/wparrayp.sxx
wparrayt.o: \
	../wparrayt.hxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../wparrayt.oxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/wparrayt.sxx
verwrap.o: \
	../ccompatc.h
tombx.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../tombx.hxx \
	../allocp.hxx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx
tofux.o: \
	../tofup.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../fhashx.hxx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx \
	../initx.hxx \
	../choosex.hxx \
        ../sxx/tofux.sxx \
        ../sxx/tofup.sxx \
	../../comm/xfrspecx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.oxx \
	../../comm/cookbkx.oxx \
	../../comm/nscottyx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../comm/recipex.oxx
tofut.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../tofut.hxx \
	../tofut.oxx \
	../initx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/tofut.sxx
testx.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../../xlatexpp/tablesx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/stepperx.oxx \
	../initx.hxx \
	../../xlatexpp/stepperx.hxx \
	../parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx
stubrcpx.o: \
	../stubrcpx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../comm/recipex.hxx \
	../../comm/recipex.oxx \
	../initx.hxx \
	../copyrcpx.oxx \
	../../comm/xfrspecx.oxx \
	../parrayx.oxx \
	../stubrcpx.oxx \
	../../disk/diskmanx.oxx \
	../../comm/nxcvrx.hxx \
        ../sxx/stubrcpx.sxx
sockptlx.o: \
	../sockptlx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../sockptlx.oxx \
	../initx.hxx \
	../../comm/portalr.hxx \
	../../comm/portalx.hxx \
	../../comm/portalx.oxx \
	../../comm/nscottyx.oxx \
	../../comm/portalr.oxx \
	../../comm/nscottyx.hxx \
	../parrayx.oxx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx \
	../sockptlx.ixx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/sockptlx.sxx
sema4x.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../sema4x.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../sema4x.oxx \
	../sema4x.ixx \
        ../sxx/sema4x.sxx
scavx.o: \
	../scavx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../scavp.hxx \
	../scavp.ixx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../parrayx.hxx \
	../tofux.hxx \
	../xunewx.hxx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx
scavt.o: \
	../scavt.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../scavp.hxx \
	../scavp.ixx \
	../scavt.oxx \
	../wparrayx.oxx \
	../parrayx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.ixx \
        ../sxx/scavt.sxx
sboxx.o: \
	../sboxx.hxx
queuesx.o: \
	../queuesx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../queuesx.ixx
psrandx.o: \
	../psrandx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../psrandx.oxx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
        ../sxx/psrandx.sxx
psrandt.o: \
	../psrandt.hxx \
	../psrandx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../psrandx.oxx \
        ../sxx/psrandt.sxx
parrayx.o: \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../parrayp.hxx \
	../wparrayx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../parrayp.oxx \
	../../xlatexpp/primvalx.hxx \
	../../xlatexpp/primvalx.ixx \
	../choosex.hxx \
	../fhashx.hxx \
        ../sxx/parrayx.sxx
parrayt.o: \
	../parrayp.hxx \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../parrayp.oxx \
	../parrayt.hxx \
	../parrayt.oxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx \
        ../sxx/parrayt.sxx
opaquex.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
opaquet.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../opaquet.hxx \
	../opaquet.oxx \
	../initx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/opaquet.sxx
loggerx.o: \
	../loggerx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../loggerx.oxx \
	../loggerx.ixx
loggert.o: \
	../loggerx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../loggerx.oxx \
	../loggerx.ixx
intvarx.o: \
	../intvarx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.ixx \
	../../comm/nxcvrx.hxx \
	../initx.hxx \
	../parrayx.oxx \
        ../sxx/intvarx.sxx
intvart.o: \
	../intvarx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.ixx \
	../initx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx
initx.o: \
	../initx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
        ../sxx/initx.sxx
initt.o: \
	../initx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../initt.hxx \
	../initt.oxx \
	../../xlatexpp/gchooksx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/initt.sxx
hsboxx.o: \
	../hsboxx.hxx \
	../xcompatx.hxx \
	../ccompatc.h
hashes.o: \
	../fhashx.hxx \
	../xcompatx.hxx \
	../ccompatc.h
gmonx.o: \
	../xcompatx.hxx \
	../ccompatc.h
garbagex.o: \
	../garbagep.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../../xlatexpp/thunkx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/thunkx.oxx \
	../initx.hxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../parrayx.oxx \
	../../comm/nxcvrx.hxx \
	../bibopx.hxx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
	../tombx.hxx \
	../diagx.hxx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx \
	../tracerc.h \
	../garbagex.ixx \
        ../sxx/garbagep.sxx
garbaget.o: \
	../garbaget.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../garbaget.oxx \
	../garbaget.ixx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx \
	../initx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/garbaget.sxx
fluidx.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../fluidp.hxx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx
fluidt.o: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx \
	../fluidt.hxx \
	../fluidt.oxx \
	../initx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/fluidt.sxx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx
filetpx.o: \
	../filetpx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../filetpx.oxx \
	../../comm/nscottyx.hxx \
	../../comm/nscottyx.oxx \
	../initx.hxx \
	../parrayx.oxx \
	../filetpp.hxx \
	../filetpp.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
        ../sxx/filetpx.sxx \
        ../sxx/filetpp.sxx
fhashx.o: \
	../fhashx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../hsboxx.hxx
fhasht.o: \
	../fhashx.hxx \
	../xcompatx.hxx \
	../ccompatc.h
diagx.o: \
	../diagx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx \
	../initx.hxx \
        ../sxx/diagx.sxx
crutcht.o: \
	../xcompatx.hxx \
	../ccompatc.h
copyrcpx.o: \
	../copyrcpx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../parrayx.oxx \
	../../comm/xfrspecx.hxx \
	../../comm/nxcvrx.hxx \
	../../comm/cookbkx.oxx \
	../../comm/nscottyx.oxx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../choosex.hxx \
        ../sxx/copyrcpx.sxx
choosex.o: \
	../choosex.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
chooset.o: \
	../choosex.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../chooset.hxx \
	../chooset.oxx \
	../initx.hxx \
	../../xlatexpp/gchooksx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx \
        ../sxx/chooset.sxx
cbombx.o: \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx \
	../cbombc.h
bombx.o: \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx
bombt.o: \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx \
	../bombt.hxx \
	../bombt.ixx
bibopx.o: \
	../bibopp.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bibopx.hxx \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx \
	../../xlatexpp/stepperx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/stepperx.oxx \
	../initx.hxx \
	../parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../bibopp.ixx \
        ../sxx/bibopx.sxx \
        ../sxx/bibopp.sxx
bibopt.o: \
	../bibopt.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../bibopp.hxx \
	../bibopx.hxx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx \
	../../xlatexpp/stepperx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/stepperx.oxx \
	../initx.hxx \
	../parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../../stubble/copy.hf \
	../copyrcpx.hxx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../../comm/xfrspecx.oxx \
	../../comm/nxcvrx.hxx \
	../parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../bibopp.ixx \
	../bibopt.oxx \
        ../sxx/bibopt.sxx
allocx.o: \
	../xcompatx.hxx \
	../ccompatc.h \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../initx.hxx \
	../allocp.hxx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx \
	../tombx.hxx
alloct.o: \
	../allocp.hxx \
	../allocx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../queuesx.hxx \
	../queuesx.ixx \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../alloct.hxx \
	../alloct.oxx \
	../initx.hxx \
        ../sxx/alloct.sxx
xmemoryc.o: \
	../xmemoryc.h \
	../ccompatc.h
tracerc.o: \
	../tracerc.h
ccompatt.o: \
	../ccompatc.h
ccompatc.o: \
	../ccompatc.h
cbombt.o: \
	../cbombc.h \
	../bombc.h \
	../ccompatc.h
../sxx/xunewx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h
../sxx/xppx.sxx: \
	../ccompatc.h \
	../xcompatx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../initx.hxx \
	../tofux.hxx \
	../xunewx.hxx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../sema4x.hxx \
	../sema4x.oxx \
	../sema4x.ixx \
	../choosex.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/setx.hxx \
	../../xlatexpp/setx.oxx \
	../../xlatexpp/setp.oxx \
	../../xlatexpp/setx.ixx \
	../../xlatexpp/spacex.hxx \
	../../xlatexpp/integerx.oxx \
	../../xlatexpp/spacex.ixx \
	../../xlatexpp/spacep.hxx \
	../../xlatexpp/spacep.oxx \
	../../xlatexpp/integerx.hxx \
	../../xlatexpp/integerp.oxx \
	../../xlatexpp/integerx.ixx \
	../../xlatexpp/hspacex.hxx \
	../../xlatexpp/hspacex.oxx \
	../../xlatexpp/hspacex.ixx \
	../../xlatexpp/hspacep.hxx \
	../../xlatexpp/hspacep.oxx \
	../../xlatexpp/spacer.hxx \
	../../xlatexpp/spacer.oxx \
	../../xlatexpp/hspacep.ixx \
	../../xlatexpp/tablesx.hxx \
	../../xlatexpp/tablesx.oxx \
	../../xlatexpp/hashtabx.oxx \
	../../xlatexpp/inttabx.oxx \
	../../xlatexpp/tablesx.ixx \
	../../xlatexpp/inttabx.hxx \
	../../xlatexpp/arrayx.hxx \
	../../xlatexpp/arrayx.oxx \
	../../xlatexpp/arrayx.ixx \
	../../xlatexpp/hashtabx.hxx \
	../../xlatexpp/tabtoolx.oxx \
	../../xlatexpp/hashtabx.ixx \
	../../xlatexpp/hashtabp.hxx \
	../../xlatexpp/hashtabp.oxx \
	../../xlatexpp/tabentx.oxx
../sxx/xcompatx.sxx: \
	../ccompatc.h
../sxx/wparrayx.sxx: \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../initx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx
../sxx/wparrayt.sxx: \
	../wparrayx.hxx \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../initx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../wparrayt.oxx
../sxx/wparrayp.sxx: \
	../wparrayx.hxx \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../initx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx
../sxx/tombx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h
../sxx/tofux.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
../sxx/tofut.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../tofut.oxx
../sxx/tofup.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
../sxx/stubrcpx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../comm/recipex.hxx \
	../../comm/recipex.oxx \
	../initx.hxx \
	../copyrcpx.oxx \
	../../comm/xfrspecx.oxx \
	../parrayx.oxx \
	../stubrcpx.oxx \
	../../disk/diskmanx.oxx
../sxx/sockptlx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../sockptlx.oxx \
	../initx.hxx \
	../../comm/portalr.hxx \
	../../comm/portalx.hxx \
	../../comm/portalx.oxx \
	../../comm/nscottyx.oxx \
	../../comm/portalr.oxx \
	../../comm/nscottyx.hxx \
	../parrayx.oxx \
	../allocx.hxx \
	../queuesx.hxx \
	../queuesx.ixx
../sxx/sema4x.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../sema4x.oxx \
	../sema4x.ixx
../sxx/scavx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx
../sxx/scavt.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../scavp.hxx \
	../scavp.ixx \
	../scavt.oxx \
	../wparrayx.oxx \
	../parrayx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../initx.hxx \
	../wparrayx.ixx
../sxx/scavp.sxx: \
	../scavp.ixx \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx
../sxx/regressx.sxx: \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx
../sxx/queuesx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../queuesx.ixx
../sxx/psrandx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../psrandx.oxx
../sxx/psrandt.sxx: \
	../psrandx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../psrandx.oxx
../sxx/parrayx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx
../sxx/parrayt.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../parrayt.oxx
../sxx/parrayp.sxx: \
	../parrayx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../wparrayx.hxx \
	../initx.hxx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../parrayp.oxx
../sxx/opaquex.sxx: \
	../opaquex.ixx \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx
../sxx/opaquet.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../opaquet.oxx
../sxx/mortalx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../mortalx.ixx
../sxx/loggerx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../loggerx.oxx \
	../loggerx.ixx
../sxx/intvarx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.ixx
../sxx/initx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
../sxx/initt.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../initt.oxx
../sxx/hsboxx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h
../sxx/garbagex.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../bibopx.oxx \
	../garbagex.ixx
../sxx/garbaget.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../garbaget.oxx \
	../garbaget.ixx
../sxx/garbagep.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../../xlatexpp/thunkx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/thunkx.oxx \
	../initx.hxx \
	../bibopx.hxx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx \
	../../xlatexpp/gchooksx.hxx \
	../../xlatexpp/gchooksx.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../parrayx.oxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx \
	../../xlatexpp/primtabx.oxx \
	../../xlatexpp/stepperx.oxx \
	../../xlatexpp/gchooksx.ixx \
	../../xlatexpp/primtabx.hxx \
	../../xlatexpp/stepperx.hxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../../xlatexpp/primtabx.ixx \
	../fhashx.hxx
../sxx/fluidx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../xunewx.hxx \
	../fluidx.oxx \
	../fluidx.hxx \
	../fluidx.ixx
../sxx/fluidt.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx \
	../fluidt.oxx
../sxx/fluidp.sxx: \
	../fluidx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../xunewx.hxx \
	../fluidx.oxx \
	../fluidx.ixx
../sxx/filetpx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../filetpx.oxx \
	../../comm/nscottyx.hxx \
	../../comm/nscottyx.oxx \
	../initx.hxx \
	../parrayx.oxx
../sxx/filetpp.sxx: \
	../filetpx.hxx \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../filetpx.oxx \
	../../comm/nscottyx.hxx \
	../../comm/nscottyx.oxx \
	../initx.hxx \
	../parrayx.oxx \
	../filetpp.oxx \
	../wparrayx.hxx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../wparrayx.oxx \
	../wparrayx.ixx
../sxx/fhashx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h
../sxx/diagx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../fluidx.hxx \
	../fluidx.oxx \
	../fluidx.ixx
../sxx/copyrcpx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../intvarx.hxx \
	../intvarx.ixx \
	../copyrcpx.oxx \
	../../comm/recipex.oxx \
	../../comm/recipex.hxx \
	../initx.hxx \
	../../comm/xfrspecx.oxx \
	../parrayx.oxx
../sxx/choosex.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
../sxx/chooset.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../chooset.oxx
../sxx/bombx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx
../sxx/bombt.sxx: \
	../bombx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../bombc.h \
	../bombx.ixx
../sxx/bibopx.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx
../sxx/bibopt.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../bibopp.hxx \
	../bibopx.hxx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx \
	../../xlatexpp/stepperx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/stepperx.oxx \
	../initx.hxx \
	../parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../bibopp.ixx \
	../bibopt.oxx
../sxx/bibopp.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../bibopx.hxx \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../bibopx.oxx \
	../bibopp.oxx \
	../loggerx.hxx \
	../loggerx.oxx \
	../loggerx.ixx \
	../bibopx.ixx \
	../../xlatexpp/stepperx.hxx \
	../intvarx.hxx \
	../intvarx.ixx \
	../../xlatexpp/stepperx.oxx \
	../initx.hxx \
	../parrayx.oxx \
	../../xlatexpp/spacex.oxx \
	../../xlatexpp/stepperp.oxx \
	../../xlatexpp/stepperx.ixx \
	../parrayx.hxx \
	../../xlatexpp/primvalx.oxx \
	../parrayx.ixx \
	../../xlatexpp/stepperp.hxx \
	../../xlatexpp/cachex.oxx \
	../bibopp.ixx
../sxx/allocx.sxx: \
	../xcompatx.hxx \
	../ccompatc.h \
	../queuesx.hxx \
	../queuesx.ixx
../sxx/alloct.sxx: \
	../tofux.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx \
	../alloct.oxx
../sxx/allocp.sxx: \
	../allocx.hxx \
	../xcompatx.hxx \
	../ccompatc.h \
	../queuesx.hxx \
	../queuesx.ixx \
	../tofux.hxx \
	../xunewx.hxx \
	../bombx.hxx \
	../bombc.h \
	../bombx.ixx \
	../scavx.hxx \
	../scavx.oxx \
	../scavp.oxx \
	../scavx.ixx \
	../opaquex.hxx \
	../opaquex.ixx \
	../tofux.oxx \
	../../comm/nxcvrx.oxx \
	../tofux.ixx \
	../opaque2x.ixx
sxx:        ../sxx/wparrayx.sxx \
        ../sxx/wparrayp.sxx \
        ../sxx/wparrayt.sxx \
        ../sxx/tofux.sxx \
        ../sxx/tofup.sxx \
        ../sxx/tofut.sxx \
        ../sxx/stubrcpx.sxx \
        ../sxx/sockptlx.sxx \
        ../sxx/sema4x.sxx \
        ../sxx/scavt.sxx \
        ../sxx/psrandx.sxx \
        ../sxx/psrandt.sxx \
        ../sxx/parrayx.sxx \
        ../sxx/parrayt.sxx \
        ../sxx/opaquet.sxx \
        ../sxx/intvarx.sxx \
        ../sxx/initx.sxx \
        ../sxx/initt.sxx \
        ../sxx/garbagep.sxx \
        ../sxx/garbaget.sxx \
        ../sxx/fluidt.sxx \
        ../sxx/filetpx.sxx \
        ../sxx/filetpp.sxx \
        ../sxx/diagx.sxx \
        ../sxx/copyrcpx.sxx \
        ../sxx/chooset.sxx \
        ../sxx/bibopx.sxx \
        ../sxx/bibopp.sxx \
        ../sxx/bibopt.sxx \
        ../sxx/alloct.sxx \
