'From Objectworks for Smalltalk-80(tm), Version 2.5 of 29 July 1989 on 22 March 1995 at 8:51:53 pm'!

ClassRelatedChange subclass: #ClassChange
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'System-Changes'!
ClassChange comment:
'Class ClassChange represents a change to some part of a class definition (actual definition, comment, name, ...) as opposed to a change to a method within a class.  As this class currently adds no further information, it is being used to fulfill class hierarchy symmetry with MethodChange.'!
