'From Objectworks for Smalltalk-80(tm), Version 2.5 of 29 July 1989 on 22 March 1995 at 8:48:59 pm'!

FormBitmap variableByteSubclass: #DisplayBitmap
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Graphics-Support'!
DisplayBitmap comment:
'Class DisplayBitmap is a subclass of Bitmap that is used to indicate the particular bitmap which is being displayed, so that various implementations can treat it specially.  It adds no protocol.

Instance Variables: *word indexed*'!
