'From Objectworks for Smalltalk-80(tm), Version 2.5 of 29 July 1989 on 22 March 1995 at 9:02:39 pm'!

Tester subclass: #OrderedRegionTester
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Xanadu-Testing'!


!OrderedRegionTester methodsFor: 'running tests'!

{void} allTestsOn: aStream {ostream reference}

	"OrderedRegionTester runTest: #allTestsOn:"

	self test1On: aStream! !