'From Objectworks for Smalltalk-80(tm), Version 2.5 of 29 July 1989 on 22 March 1995 at 8:53:10 pm'!

XnModel subclass: #XnVm
	instanceVariableNames: 'stuff lengthOfStuff '
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Compositors-Support'!


!XnVm methodsFor: 'instance creation'!

create! !

!XnVm methodsFor: 'accessing'!

{XChar} accessStuff: xAddress{IntegerVar} with: length {IntegerVar}! !