17	/usr/lib/acct/acctprc1
17	/usr/lib/acct/acctprc2
1	/usr/lib/acct/prctmp
3	/usr/share/man/man8/acctprc.8
1	/usr/share/man/man8/acctprc1.8
1	/usr/share/man/man8/acctprc2.8
1	/usr/share/man/man8/prctmp.8
26	/Fhypatia/roger/f9/robj/XAT/protocol/client.prc
3	/Fhypatia/roger/f9/robj/XAT/protocol/modules.prc
27	/Fhypatia/roger/f9/robj/XAT/protocol/ptype.prc
24	/Fhypatia/roger/f9/robj/src/promise/checklist.prc
25	/Fhypatia/roger/f9/robj/src/promise/client.prc
27	/Fhypatia/roger/f9/robj/src/promise/ptype.prc
6	/Fhypatia/roger/prod/xhs/src/image/client.prc.gz
1	/Fhypatia/roger/prod/xhs/src.roger2/image/client.prc
26	/Fhypatia/roger/prod/xhs/src.roger2/image/client.prc.foo
25	/Fhypatia/roger/prod/xhs/src.roger2/promise/client.prc
27	/Fhypatia/roger/prod/xhs/src.roger2/promise/ptype.prc
6	/Fhypatia/roger/prod/xhs/src.roger2/promise/save/client.prc.gz
24	/Fhypatia/roger/prod/xhs/src.roger2/promise/checklist.prc
1	/Fhypatia/roger/prod/xhs/src.roger2/image.chris/client.prc
25	/Fhypatia/roger/prod/xhs/src.markm/image/client.prc
26	/Fhypatia/roger/prod/xhs/src.markm/image/client.prc.foo
6	/Fhypatia/roger/prod/xhs/src.markm/promise/ptype.prc.gz
6	/Fhypatia/roger/prod/xhs/src.markm/promise/client.prc.gz
6	/Fhypatia/roger/prod/xhs/src.markm/promise/save/client.prc.gz
6	/Fhypatia/roger/prod/xhs/src.markm/promise/checklist.prc.gz
1	/Fhypatia/roger/prod/XAT/C++/libxu/sun/modules.prc
1	/Fhypatia/roger/prod/XAT/C++/libxu/sun/client.prc
26	/Fhypatia/roger/prod/XAT/protocol/client.prc
3	/Fhypatia/roger/prod/XAT/protocol/modules.prc
27	/Fhypatia/roger/prod/XAT/protocol/ptype.prc
1	/Fhypatia/roger2/prod/xhs/src/image/client.prc
6	/Fhypatia/roger2/prod/xhs/src/promise/client.prc.gz
6	/Fhypatia/roger2/prod/xhs/src/promise/ptype.prc.gz
6	/Fhypatia/roger2/prod/xhs/src/promise/save/client.prc.gz
6	/Fhypatia/roger2/prod/xhs/src/promise/checklist.prc.gz
6	/Fhypatia/roger2/prod/XAT/C++/libxu/sun/client.prc.gz
1	/Fhypatia/roger2/prod/XAT/C++/libxu/sun/modules.prc.gz
6	/Fhypatia/roger2/prod/XAT/C++/libxu/client.prc.gz
6	/Fhypatia/roger2/prod/XAT/protocol/ptype.prc.gz
6	/Fhypatia/roger2/prod/XAT/protocol/client.prc.gz
1	/Fhypatia/roger2/prod/XAT/protocol/modules.prc.gz
1	/Fmisc/rogerftp/dot.ncftprc.gz
24	/Fmisc/newlocal/lib/pps/prc
24	/Fmisc/newlocal/share/lib/prc
